### ISSUE TITLE
tolerance in meters or degrees

### ISSUE THREAD

**Issue by prasadrajuv** [alexpechkarev/geometry-library#14]
documenation showing tolerance in meters in example as degrees. i think meters or correct its working. and isLocationOnEdge returns 1 on true nothing on false

**Comment by alexpechkarev** [comment]
Hi @prasadrajuv,

Apologies for the late response.

Please can you try validating response from `isLocationOnEdge ` using `empty()`  function ?

Regards,
Alexander
