### ISSUE TITLE
Intersection of two direction given start points and bearings

### ISSUE THREAD

**Issue by eov-oleg** [alexpechkarev/geometry-library#18]
Hello!
How to I can calculate intersection point of two line with point1, direction1 and point2, direction2
Thanks!
![image](https://github.com/alexpechkarev/geometry-library/assets/61245199/c5289813-7338-4f8b-b7a9-36f29b728353)

**Comment by alexpechkarev** [comment]
Hi @eov-oleg ,
This repository is PHP port from [android-maps-utils](https://github.com/googlemaps/android-maps-utils) repo.
