### ISSUE TITLE
Call the function isLocationOnEdge with parameter $ geodesic = false

### ISSUE THREAD

**Issue by marczeo** [alexpechkarev/geometry-library#3]
Hello, 
When I called the function, the response was ` Use of undefined constant lng3 - assumed 'lng3'` , I saw the function declaration and missing the "$" before the variable $lng3 and the variable $lng1.

The error was in the file "PolyUtil.php" line 202

**Comment by alexpechkarev** [comment]
Hi @marczeo ,

Thanks for pointing out, the error has been amended as per your suggestion.

Regards
