### ISSUE TITLE
How do I include into a php file?

### ISSUE THREAD

**Issue by haywood1** [alexpechkarev/geometry-library#4]
I have used the following code to add the SphericalUtil into the php file but giving this error: `Class 'SphericalUtil' not found`. Hopefully someone can help.

Do I need to use composer? Is it possible not to?

```
 include('geometry-library/SphericalUtil.php');
        $HexLib= new SphericalUtil();
```

**Comment by alexpechkarev** [comment]
Hi @haywood1 ,

It will be best to use composer to install the package as  SphericalUtil.php uses use GeometryLibrary\MathUtil.php.

Hope this helps.
Regards,
Alexander
